### ISSUE TITLE
Support adding packages for specific groups

### ISSUE THREAD

**Issue by sjpb** [stackhpc/ansible-slurm-appliance#105]
At the moment we're (slightly mis)-using the `openhpc_packages` variable to install "user" packages on nodes as well. It'd be better if this was done separately and in such a way that packages can be targeted to specific groups, e.g. "login + compute" , or "gpu" or "control only". 

Suggested interface:

```yaml
cluster_packages: # so play runs on group `cluster`
  - groups: [login, compute] # this then used to select specific nodes
    packages: ....
  - groups: gpu
    packages ...
```

We could get a significant speedup by building a node-specific list of packages in the same way the openhpc role does, so the actual `dnf/yum install` step runs in parallel on all nodes at once (with different lists) rather than looping through the list sequentially.

@jovial, @mkjpryor any thoughts?
