### ISSUE TITLE
Is prometheus_targets correct

### ISSUE THREAD

**Issue by sjpb** [stackhpc/ansible-slurm-appliance#115]
In https://github.com/stackhpc/ansible-slurm-appliance/blob/main/environments/common/inventory/group_vars/all/prometheus.yml#L16, the `prometheus_targets` are set to the `all` group, omitting `localhost`. Should this group actually be `node_exporter` as defined [here](https://github.com/stackhpc/ansible-slurm-appliance/blob/main/environments/common/inventory/groups#L60)?

**Comment by sjpb** [comment]
Actually currently /etc/prometheus/prometheus.yml looks like e.g.:

So I'm not sure it's working anyway

```yaml
scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - dev-control:9090
  - job_name: grafana
    static_configs:
    - targets:
      - dev-control:3000
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/node.yml
    job_name: node
    params:
      collect[]:
      - netdev
      - cpu
      - meminfo
      - infiniband
      - cpufreq
    relabel_configs:
    - regex: (.*):.*
      replacement: ${1}
      separator: ':'
      source_labels:
      - __address__
      target_label: instance
    scrape_interval: 30s
    scrape_timeout: 20s
```
