### ISSUE TITLE
Use slurmdb directly as grafana datasource

### ISSUE THREAD

**Issue by sjpb** [stackhpc/ansible-slurm-appliance#146]
Could potentially use the mysql plugin https://grafana.com/docs/grafana/latest/datasources/mysql/ to query the slurmdb directly, rather than having to use slurm_stats/filebeat/elasticsearch, which would mean we could also ditch podman.

However `slurm_stats` does also do some munging of the `sacct` output, e.g. https://github.com/stackhpc/slurm-openstack-tools/blob/bacbf41fd276d4478c44ec5356d048db89128b67/slurm_openstack_tools/sacct.py#L72. Might be hard to replicate in grafana.

**Comment by sjpb** [comment]
@jovial for info.

**Comment by sjpb** [comment]
Useful: https://wiki.fysik.dtu.dk/niflheim/Slurm_database#slurm-database-tables

**Comment by sjpb** [comment]
Needs something like this adding

```
grafana_datasources:
  - name: slurmdb
    ds_type: mysql
    ds_url: "{{ groups['control'] | first }}:6819" # {{ openhpc_slurmdbd_host}}:{{openhpc_slurmdbd_port}} # TODO: need to make properly configurable
    database: slurm_acct_db # openhpc_slurmdbd_mysql_database
    user: slurm
    password: "{{ vault_mysql_slurm_password }}"
```

although I can't seem to query this ..
