### ISSUE TITLE
Additional OOD files app paths broken?

### ISSUE THREAD

**Issue by sjpb** [stackhpc/ansible-slurm-appliance#322]
Update to v3 didn't address
See https://osc.github.io/ood-documentation/latest/release-notes/v3.0-release-notes.html#autoloading-during-initialization-is-deprecated

for ondemand openondemand_filesapp_paths - see `ansible/roles/openondemand/templates/files_shortcuts.rb.j2`

**Comment by sjpb** [comment]
Just tested this on arcus, using a `/scratch` directory as shown below, and actually it does appear / is usable (modulo ownership error) from the Files App.

```
environments/.stackhpc/inventory/group_vars/all/nfs.yml:
nfs_configurations:
  - comment: Export /exports/home from Slurm control node as /home
    nfs_enable:
        server:  "{{ inventory_hostname in groups['control'] }}"
        # Don't mount share on server where it is exported from...
        # Could do something like `nfs_clients: "{{ 'nfs_servers' not in group_names }}"` instead.
        clients: "{{ inventory_hostname in groups['cluster'] and inventory_hostname not in groups['control'] }}"
    nfs_server: "{{ nfs_server_default }}"
    nfs_export: "/exports/home" # assumes skeleton TF is being used
    nfs_client_mnt_point: "/home"
  - comment: Test mount for openondemand_filesapp_paths
    nfs_enable:
      server:  "{{ inventory_hostname in groups['control'] }}"
      clients: "{{ inventory_hostname in groups['cluster'] and inventory_hostname not in groups['control'] }}"
    nfs_server: "{{ nfs_server_default }}"
    nfs_export: "/exports/scratch"
    nfs_client_mnt_point: "/scratch"
```

```
environments/.stackhpc/inventory/group_vars/openondemand/overrides.yml:
...
openondemand_filesapp_paths:
  - /scratch
```
