### ISSUE TITLE
Revised basic_users approach broken for client config

### ISSUE THREAD

**Issue by sjpb** [stackhpc/ansible-slurm-appliance#625]
Client has 

```yaml
basic_users_users_grid_defaults:
  create_home: true
  generate_ssh_key: false
```

which gets inserted into each basic_user_users directory. These users have local homedirs which are not on the shared filesystem.

With https://github.com/stackhpc/ansible-slurm-appliance/pull/599 there is no way to modify their config to achieive this.
