### ISSUE TITLE
Image build fails because of undefined cluster_compute_groups

### ISSUE THREAD

**Issue by priteau** [stackhpc/ansible-slurm-appliance#680]
Packer image build fails because it refers to variable `cluster_compute_groups` defined by OpenTofu.

```
    openstack.openhpc: TASK [osc.ood : Install OOD apps] **********************************************                                                                                                                                                                                                                                                                     
    openstack.openhpc: task path: /home/rocky/image-build/ansible/roles/osc.ood/tasks/install-apps.yml:1                                                                                                                                                                                                                                                                    
    openstack.openhpc: The conditional check 'ood_install_apps is defined' failed. The error was: error while evaluating conditional (ood_install_apps is defined): {{ ood_install_apps_defaults if openondemand_jupyter_partition | default(none) else {} }}: {{ openhpc_partitions[0]['name'] }}: {{ openhpc_user_partitions + ([openhpc_rebuild_partition] if groups['reb
uild'] | length > 0 else []) }}: {{ openhpc_nodegroups }}: {{ cluster_compute_groups | map('community.general.dict_kv', 'name') }}: 'cluster_compute_groups' is undefined                                                                                                                                                                                                   
    openstack.openhpc:                                                                                                                                                                
    openstack.openhpc: The error appears to be in '/home/rocky/image-build/ansible/roles/osc.ood/tasks/install-apps.yml': line 1, column 3, but may
    openstack.openhpc: be elsewhere in the file depending on the exact syntax problem.                                                                                                
    openstack.openhpc:                                                                                                                                                                                                                                                                                                                                                      
    openstack.openhpc: The offending line appears to be:                                                                                                                              
    openstack.openhpc:                                                                                                                                                                                                                                                                                                                                                      
    openstack.openhpc:                                                                                                                                                                
    openstack.openhpc: - name: Install OOD apps                                                                                                                                                                                                                                                                                                                             
    openstack.openhpc:   ^ here                                                       
    openstack.openhpc: fatal: [default]: FAILED! => {}                                                                                                                                
    openstack.openhpc:                                                                                                                                                                                                                                                                                                                                                      
    openstack.openhpc: MSG:                                                                                                                                                           
    openstack.openhpc:                                                                                                                                                                                                                                                                                                                                                      
    openstack.openhpc: {{ ood_install_apps_defaults if openondemand_jupyter_partition | default(none) else {} }}: {{ openhpc_partitions[0]['name'] }}: {{ openhpc_user_partitions + ([openhpc_rebuild_partition] if groups['rebuild'] | length > 0 else []) }}: {{ openhpc_nodegroups }}: {{ cluster_compute_groups | map('community.general.dict_kv', 'name') }}: 'cluster_
compute_groups' is undefined                                                                                                                                                                                                                                                                                                                                                
    openstack.openhpc:                                                                                                                                                                
```
